### ISSUE TITLE
move to SimPEG org?

### ISSUE THREAD

**Issue by lheagy** [simpeg/pymatsolver#21]
Since we are moving towards having SimPEG rely on pymatsolver for all of the solvers (see simpeg/simpeg#672), would it make sense to bring this repo over to the SimPEG org? We can make sure the docs are linked, pypi deploys automated, etc.

**Comment by rowanc1** [comment]
- [ ] ensure rtd is up to date and deploy still works.

**Comment by lheagy** [comment]
RTD isn't up to date yet. @rowanc1: would you mind updating and / or adding me? (LindseyH on rtfd)

**Comment by rowanc1** [comment]
Added you and updated the config. Hope that works!
