### ISSUE TITLE
Use newer, non-mkl, version of PARDISO

### ISSUE THREAD

**Issue by prisae** [simpeg/pymatsolver#28]
To follow up on the Slack-discussion and to not forget about it.

For more info: https://www.pardiso-project.org

From the website:
> Important: Please note that the Intel MKL version of PARDISO is based on our version from 2006 and that a lot of new features and improvements of PARDISO are not available in the Intel MKL library.

In their examples this means a **speed-up factor of anything between 1.7 and 26**, see the comparison charts in the [feature-list](https://www.pardiso-project.org#features).

**Comment by jcapriot** [comment]
I was looking at this a little while ago when I was writing up my own cython interface to intel's pardiso. Do you know what there licensing scheme is? There seems to be at least a free single-user academic license, but what is the corporate license?

**Comment by prisae** [comment]
Ha! No idea. As it was in the mkl I assumed it was open-source. That was wrong. So I guess this issue is more a 'nice-to-have' request then anything realistic...

https://www.pardiso-project.org/#download

**Comment by prisae** [comment]
Thanks @jcapriot . I looked at it again, and there is really nothing we can to, the mkl version it is then. Closing here.
