### ISSUE TITLE
`is_summetric` with `SolverLU`

### ISSUE THREAD

**Issue by prisae** [simpeg/pymatsolver#32]
Copying over from Slack:

Dieter:
> Alfredo Sanchez brought a problem to my attention, and I think it is a bug: It is about the following example: https://docs.simpeg.xyz/content/tutorials/05-dcr/plot_inv_2_dcr2d.html Running it with PARDISO works fine. However, running it with SolverLU results in:

![Selection_001](https://user-images.githubusercontent.com/8020943/85821060-1422b980-b778-11ea-9ad9-862169bb07db.png)

Lindsey:
> hmm, yes, I think there is an inconsistency between the kwargs that splu / pardiso expect (the is_symmetric flag in Pardiso changes how the matrix is factored, whereas it is not an option in splu https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.splu.html)
> This is something we should fix in the pymatsolver layer

**Comment by prisae** [comment]
Out of curiosity: was it resolved (when/where/how) or is it closed because it is a `wontfix` (or is it considered to not be a bug)?

**Comment by jcapriot** [comment]
Now, extra unused arguments are warned against, and then ignored, instead of causing errors.
i.e. this would have raised a warning saying that `is_symmetric` is unused.
